### ISSUE TITLE
[question] Is there limit for GET requests?

### ISSUE THREAD

**Issue by a3s** [MineSkin/api.mineskin.org#116]
I want to write a plugin that allows players to select existing skin on mineskin.org.
Can I just request its texture data by ID from site?

**Comment by InventivetalentDev** [comment]
Nope, no limits on get requests! :) 
Though you might want to cache the data locally anyway.

**Comment by a3s** [comment]
Just to clarify, I want to do `get/id/<id>` requests. It is not documented and I guess it is only used by mineskin frontend. 
Am I allowed to use it?

**Comment by InventivetalentDev** [comment]
Yeah sure! Feel free to use `get/list` as well if you need it

**Comment by a3s** [comment]
OK, thank you and have a good day!
