### ISSUE TITLE
Some skins are always gives 429 and 204 error code.

### ISSUE THREAD

**Issue by ygtdmn** [MineSkin/api.mineskin.org#15]
Hello i use MineSkin api in my server to change player skins.

But some skins are always gives 204(no content) error code and if i try to refresh the page it gives 429(too many request) error code. I never can't get these skins.

Here following players lives that issue:
- _Anshton -  https://api.mineskin.org/generate/user/8a9f2fe0-cf90-3819-b473-793d4dd431bc
- ReachBurakk - http://api.mineskin.org/generate/user/3748f190-6191-3e25-bc90-8e85b98d05a9

They have skins and it is visible in Minecraft premium servers. Also some sites like mcskinsearch.com can see their skins as well.

**Comment by InventivetalentDev** [comment]
Searching for the two names on NameMC it seems like the UUIDs you're using are wrong:  

_Anshton ->1edc4565-717e-4496-96a5-4c7214fd91d3 (https://namemc.com/profile/_Anshton.1) 
ReachBurakk -> bd78aceb-d9f1-4f12-b03d-ded20dcb8eaa (https://namemc.com/profile/ReachBurakk.1)

**Comment by ygtdmn** [comment]
Sorry, it was a non-premium server and seems like i was trying to use wrong uuid.
