### ISSUE TITLE
Uploaded skins are replaced with random skins from the global gallery

### ISSUE THREAD

**Issue by tomas-correia** [MineSkin/api.mineskin.org#157]
I have tried generating many skins but only one seems to actually be successfully applied to my player. When I try generating the other ones and then try to apply them to my player once I join, it seems to get a random skin from Mineskin's global gallery. First time it happened I logged on with a shrek skin lol.
If I go to the gallery and try to download one of my own skins (any of the ones that don't work), it downloads a random skin file from the global gallery.
This is extremely annoying and it's driving me insane. Do you have any idea what could be causing this? Again, so far only ONE skin has actually worked. And it's nothing special from the others.

Here's an example. It was supposed to generate according to this skin
![image](https://user-images.githubusercontent.com/20492365/80200588-c1fbd580-861a-11ea-984a-d39566a8dad8.png)
But it instead randomly gave me this
![image](https://user-images.githubusercontent.com/20492365/80200486-9973db80-861a-11ea-8419-96fc9ed30d92.png)

**Comment by InventivetalentDev** [comment]
It's driving me insane as well, no worries.  
Mojang seems to be having some issues at the moment causing theses issues.  
I made a couple of changes earlier which might help reduce how often this happens, but no guarantees.

**Comment by xknat** [comment]
Can confirm.
We from SkinsRestorer are now also getting reports.
Uploading `https://i.imgur.com/UbMwWCF.png`
Gives `http://textures.minecraft.net/texture/33f0306e3488b95a8e29307171b273567de87a651dd1ac6adeb4d6cc67bcf216`

**Comment by tomas-correia** [comment]
Okay. Good to know that at least it's something temporary.

**Comment by tomas-correia** [comment]
Also @InventivetalentDev could you please let us know when things come back to normal again?

**Comment by InventivetalentDev** [comment]
will do. hoping this will resolve itself soon myself.

**Comment by s0nify** [comment]
any news?

**Comment by InventivetalentDev** [comment]
I'm not sure, to be honest. I wanna say that it's working okayish again, but I guess time will tell.  
I've tried with a couple of random textures and some skins from minecraftskins.com and they seem to have generated the correct data.  
There might also be the issue of the wrongly generated textures cluttering the database now with the wrong hashes assigned to them, so it might return other textures based on that.  
 

But, I can only test so much, so I'd like to ask you as the users of mineskin to let me know if you run into similar issues again (feel free to post here or on discord). Please also include some info about the image and types generated - if possible, ofc - so I can try and track them down. Thanks!

**Comment by InventivetalentDev** [comment]
Since this seems related, I'm guessing this is probably also resolved. https://twitter.com/namemc_com/status/1254092487498424320?s=20

**Comment by tomas-correia** [comment]
Yeah. So far I've only tested one skin (that didn't work earlier) and it works now. Can't confirm if it works with any one, though. 
So... should I mark this as solved?

**Comment by InventivetalentDev** [comment]
Let's keep it open for a couple more days and see if it is resolved, then we can close it c:

**Comment by erickskrauch** [comment]
Hello from the [Ely.by](https://ely.by)!

[Our service for generating signed textures](https://ely.by/server-skins-system) has faced the same problem. I [investigated and found](https://twitter.com/erickskrauch/status/1253337540280508422) out that now the [request for user's textures](https://wiki.vg/Mojang_API#UUID_-.3E_Profile_.2B_Skin.2FCape) has no rate limit (except the general limit of 100rps), but has a cache. And this cache works quite aggressively: it resets its timeout after each access to textures. According to my observations, the caching time is set to 5 minutes, but if you continue to make texture queries, you can get old textures for half an hour, an hour, or even more.

I am also interested in finding solutions to this problem. I'm experimenting a lot with Mojang's APIs, so if you have any ideas to solve this problem, I would be happy to share our experiences.

**Comment by InventivetalentDev** [comment]
Thanks for the info!  
I've tried a couple of times over the last few days and it seems to be working fine again - though I did increase the delay in between requests for individual accounts quite aggressively, so that might've helped.  
Fingers crossed this will work out for now.

**Comment by xknat** [comment]
How are the accounts vs request on peak times?
Are there enough accounts??
How long is the average waiting time?

**Comment by tomas-correia** [comment]
Nah. At least it hasn't happened again. Thank you all for your collaboration!
