### ISSUE TITLE
Not generating right skin on upload (hash collision?)

### ISSUE THREAD

**Issue by SpraxDev** [MineSkin/api.mineskin.org#160]
## What steps will reproduce the problem?  
1. Go on MineSkin.org and upload ![IMG-20180331-WA0002](https://user-images.githubusercontent.com/7331598/80381669-90487000-88a1-11ea-815a-226d0641a41f.png) without any additional settings
2. You should be seeing the skin 479376871 or 628530970 when selectiong alex/slim model on upload

## What were you expecting to happen? What happened instead?  
To be redirected to the right skin (and it not to differ from steve/alex models o.0 Just found it out now by luck).
Editing the file a bit results in the right skin generated: ![OBS-VirtualCam2 0 4-Installer](https://user-images.githubusercontent.com/7331598/80382190-457b2800-88a2-11ea-8248-f8b97db539e1.png)

## Some more information
Found this skin in my Google Photos gallery extremely compressed and as jpg. So its original quality is lost and maybe some voodo google compression has been applied 🤷‍♂️

**Comment by InventivetalentDev** [comment]
So 479376871 seems to be just a case of the texture containing white as the outer layer (so it's rendered white).  
Though 628530970 is actually a completely different texture.

**Comment by SpraxDev** [comment]
My bad 😂 Forgot about the outer layer being white but choosing the slim model affecting the resulting skin is still weird o.0

**Comment by InventivetalentDev** [comment]
yeah the one hashed with the alex model was indeed the wrong hash; fixed it manually for now.
