### ISSUE TITLE
Links to skins from namemc.com do not work.

### ISSUE THREAD

**Issue by sammko** [MineSkin/api.mineskin.org#182]
Links to skins from namemc.com do not work. For example `https://namemc.com/texture/266c152a597e9d9b.png` using
`curl -X POST https://api.mineskin.org/generate/url --data "url=https://namemc.com/texture/266c152a597e9d9b.png"` returns
`{"error":"Failed to determine file size"}`.

The skins at namemc.com are cached via cloudflare, is it denying access to your backend? `HEAD` requests directly to the skin url from my machine using curl work just fine.

**Comment by InventivetalentDev** [comment]
Yeah looks like their CF is blocking the requests. Will look into other ways of running the checks.

**Comment by InventivetalentDev** [comment]
Also can't download the images, not sure if I can get those to work without NameMC changing something on their end.
