### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by terrarier2111** [MineSkin/api.mineskin.org#184]
## What steps will reproduce the problem?  
1. Try to understand what the wiki means with the file parameter
2. Try to upload a skin via https://api.mineskin.org/generate/upload

## What were you expecting to happen? What happened instead?  
I expected to find any kind of possibility to understand what the file parameter means because you can't send a file directly with json as a byte array or something like this you have to send it as a string in a specific format (most common is converting the byte array to base64)

**Comment by InventivetalentDev** [comment]
It uses the standard way of uploading files via multipart/form-data. Some info on what you're trying to upload from would be helpful.  
Here's an example using Jsoup: https://github.com/InventivetalentDev/MineskinClient/blob/master/src/main/java/org/mineskin/MineskinClient.java#L173

**Comment by terrarier2111** [comment]
I got it working with your link, this was very helpful, thank you!
