### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by TuxCoding** [MineSkin/api.mineskin.org#2]
Could you please improve your documentation, because there many details missing. Things I noticed:

- GET `/generate/textures.minecraft.net/texture/a2e6a3f8caea7913ab48237beea6d6a1a6f76936e3b71af4c7a08bb61c7870` -> 404
- /generate/upload -> I guess Post? How should we encode the file?
- /generate/user/:uuid -> Generates 429 error message with a 500 response code - I assume it's rate-limiting, but there is no documentation about it

**Comment by kulkalkul** [comment]
URL is broken as I see. You can test it from www.mineskin.org, it fails to load texture data from.

**Comment by TuxCoding** [comment]
@yokunjon Interesting www.* gets an 500 too.

**Comment by InventivetalentDev** [comment]
@games647 How about trying an **actual** URL, which usually also includes an URL *scheme* e.g. http or https?  

Also, requesting the URL you specified returns an 404 error by itself, so nothing wrong with MineSkin.

**Comment by TuxCoding** [comment]
@InventivetalentDev I tried that, but it looks like I did the wrong request. I just saw that you updated the wiki and the methods are POST and not GET.

**Comment by kulkalkul** [comment]
@games647 I tried it 3 days ago, couldn't figure out how to make it work.

@InventivetalentDev I sent an email about that, these don't work:
http://api.mineskin.org/generate/url?url=http://www.fr-rp.com/forum/skinler/yokunjon.png
http://api.mineskin.org/generate/http://www.fr-rp.com/forum/skinler/yokunjon.png
http://api.mineskin.org/generate?url=http://www.fr-rp.com/forum/skinler/yokunjon.png

**Comment by kulkalkul** [comment]
This works, for example:
http://api.mineskin.org/generate/user/d454a680-58ef-4f27-ba12-e646fa9ca5c6

EDIT: Okay, I see them as @games647 saw, you updated them. Thanks.

**Comment by kulkalkul** [comment]
@InventivetalentDev I'm trying to POST this, but it still doesn't work:
http://api.mineskin.org/generate/url?url=http://www.fr-rp.com/forum/skinler/yokunjon.png

Here is the response I got, it timeouts: https://hastebin.com/tezobifono.xml

Am I doing something wrong?

**Comment by Snow-Pyon** [comment]
After testing with @yokunjon, we discovered that the problem was the protocol.

@InventivetalentDev you should clarify on the wiki that only images with HTTPS protocol will work.

**Comment by InventivetalentDev** [comment]
@Snow-Pyon Pretty sure it should work with any protocol. At least it's not a design choice to only work with https.  

Although, I don't see a reason why you'd have an image host without https these days.

**Comment by Snow-Pyon** [comment]
Well, it didn't work for me nor @yokunjon using that protocol so I guess it doesn't work 100% of the times. A warning like: `Be aware that URLs with HTTP as protocol may not work` wouldn't be bad.

**Comment by InventivetalentDev** [comment]
@Snow-Pyon Are you **sure** though, that it's not an issue with the host you used?

**Comment by Snow-Pyon** [comment]
I've used this link firstly:
http://www.fr-rp.com/forum/skinler/yokunjon.png

then as I saw it didn't work no matter how I sent the request, tried uploading the image to imgur, and it did work with this link:
https://i.imgur.com/Jo0cANC.png

And then, just to be sure, tried with another image host, tinyPic which uses http as protocol:
http://oi63.tinypic.com/2kelir.jpg

And the request failed again with the same error I got the whole time: `{"error":"URL is required"}`.

**Comment by InventivetalentDev** [comment]
Tried with TinyPic - works fine: 
![](https://i.inventivetalent.org/2017/09/17/acfbf70652_Postman.png)

**Comment by InventivetalentDev** [comment]
Anyway, if need to use the API instead of the website to automatically generate the data, why do you even bother uploading it to your own host?

**Comment by kulkalkul** [comment]
I'm trying to integrate my "skin-server", there were skins which already stored, I was using them with a client in 1.7. I'll try something different, thanks.
