### ISSUE TITLE
Sometimes "nextRequest" value missing

### ISSUE THREAD

**Issue by Nan1t** [MineSkin/api.mineskin.org#227]
## What steps will reproduce the problem?  
1. Do request for upload same image multiple times.

## What were you expecting to happen? What happened instead?  
It should return `nextRequest` value, but sometimes this value missing, all other values presents.  
The last generated response for me: https://pastebin.com/0RMm5L5T

Idk how important this parameter, but as i understood, it should be guaranteed to return. Few days before it worked perfectly.

I already wrote this on discord, this was fixed quickly, but seems like not fully.

**Comment by InventivetalentDev** [comment]
Seems to have been a server-specific issue. I fixed the config on the affected server, so should properly return it now :)
