### ISSUE TITLE
Poor /get/list performance, possibly due to countDocuments

### ISSUE THREAD

**Issue by roccodev** [MineSkin/api.mineskin.org#296]
Uncached requests of the /get/list/[page] endpoint take very long (> 20 s) to load.

I suspect this is caused by the use of `countDocuments` (introduced in https://github.com/MineSkin/api.mineskin.org/commit/7c1fc1b2188ed4ba3031505581149552cc44578a).

From the MongoDB docs:
> Returns the count of documents that match the query for a collection or view. The method wraps the $group aggregation stage with a $sum expression to perform the count.

On the other hand, the `count` operation returns an estimated count, but using collection metadata.

Was there any reason for the change?

**Comment by InventivetalentDev** [comment]
`count` is deprecated. I'll look into changing it to an estimate

**Comment by roccodev** [comment]
Ah, I guess the Node.js library deprecated it in favour of the clearer `estimatedDocumentCount` / `countDocuments`.
