### ISSUE TITLE
HTTP response code: 403!

### ISSUE THREAD

**Issue by ghost** [MineSkin/api.mineskin.org#30]
Hello,

I'm having some issues with the api getting id's.

https://pastebin.com/dLaBEnN4 (Error)

Id's used:
https://api.mineskin.org/get/id/331604
https://api.mineskin.org/get/id/325014
https://api.mineskin.org/get/id/328388
https://api.mineskin.org/get/id/328391
... and like 6 more.

**Comment by InventivetalentDev** [comment]
Are you setting an User-Agent header when making requests?

**Comment by ghost** [comment]
I don't think so here are our methods:
https://pastebin.com/8x1cpi7c

**Comment by InventivetalentDev** [comment]
You can use something like this to set a User-Agent to keep cloudflare from blocking you.

**Comment by ghost** [comment]
You added cloudflare recently becase like 1 week ago we never have this issue

**Comment by InventivetalentDev** [comment]
It's been there from the beginning, just changed some settings

**Comment by ghost** [comment]
Ok, i will try adding the user-agent property, i will reply again if works with that

**Comment by ghost** [comment]
Working again thx.
