### ISSUE TITLE
API does not match OpenAPI specification

### ISSUE THREAD

**Issue by TobiasDeBruijn** [MineSkin/api.mineskin.org#327]
The Mineskin API at `https://api.mineskin.org` does not match the OpenAPI specification [here](https://rest.wiki/?https://api.mineskin.org/openapi.yml)

## Examples
- The specification mentions an API key should be included as query parameter `key`. However when this is included the API will time out
- The specification mentions that for the endpoint `POST /generate/user`, the UUID should be given in the json payload. However the real API expects it as the query parameter `uuid`.

## What were you expecting to happen?
The API should follow the OpenAPI specification, or the OpenAPI specification should be updated to match the API

**Comment by InventivetalentDev** [comment]
> should be included as query parameter key  

It also mentions that you can provided it in the header, which is also the preferred method: 
```
Authorization: Bearer myapikey
```
~~I'll have a look why it's having issues with the query one though.~~ Query key works fine for me too if the key is valid. Fixed the timeout for invalid keys.
  
    

> However the real API expects it as the query parameter uuid  

It doesn't. Works perfectly fine for me providing it in the body. Make sure you're using the correct Content-Type header.

**Comment by TobiasDeBruijn** [comment]
>It also mentions that you can provided it in the header, which is also the preferred method:  

This Bearer token, is it just the same as if I'd put the key in the query? i.e `Authorization: Bearer <API KEY>`

>It doesn't. Works perfectly fine for me providing it in the body. Make sure you're using the correct Content-Type header.  

That would be why then. I was not explicitly setting any header.

I see what my auth issue was, I had removed all allowed `User-Agents` in the API key manager. However these don't seem to persist.

**Comment by InventivetalentDev** [comment]
> is it just the same as if I'd put the key in the query  

yep.

**Comment by TobiasDeBruijn** [comment]
Awesome. Thanks for clearing up the confusing and fixing the timed out issue!
