### ISSUE TITLE
API for random skin?

### ISSUE THREAD

**Issue by Kadeluxe** [MineSkin/api.mineskin.org#369]
Hi there!

Is it possible to have an API endpoint for getting a random skin? Something like `/get/random` maybe?
I thought about querying `/get/id/<random number>` but some IDs are missing here even while being in the correct range and this method is also deprecated.

My use case is that I want to assign random skin to players who don't have custom skin.

**Comment by InventivetalentDev** [comment]
getting random skins from the database isn't very efficient, but i'll look into it!  
(numeric IDs aren't sequential btw)

**Comment by Kadeluxe** [comment]
Actually I realized I can just get random page and select random skin from results. So separate endpoint is probably not needed given its inefficiency.
