### ISSUE TITLE
Access tokens

### ISSUE THREAD

**Issue by semenishchev** [MineSkin/api.mineskin.org#370]
**Is your feature request related to a problem? Please describe.**
As minecraft requires Bearer access token to change skin, it is possible to add direct access token to account donation

**Describe the solution you'd like**
Add an option to account donation something like "Access token"

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by InventivetalentDev** [comment]
mojang access tokens aren't reliable enough, hence the login details for that.  
if you've migrated your account and login with microsoft, that's exactly what you're giving mineskin (just the access token that can be refreshed reliably, without any login details)
