### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ziceptor** [MineSkin/api.mineskin.org#4]
How to convert the signature in the blob (what reverse action we need)?
I tried base64decode, but get a non-working signature.

**Comment by InventivetalentDev** [comment]
You can't. The signature is irreversible, since it's Mojangs measure to make skins more secure for their players.

**Comment by ziceptor** [comment]
http://api.mineskin.org/get/id/102085
Signature value in base64. I assumed that it contains valid signature.
