### ISSUE TITLE
Invalid accounts

### ISSUE THREAD

**Issue by MiniDigger** [MineSkin/api.mineskin.org#5]
There seem to be quite a few invalid accounts in the system. 
What I suggest to do is to (temporaily) deactivate an account when its failed and logging it out somewhere so that you can contact the owner and ask what happened.
should be easy to filter for the error msg "Authentication failed - Invalid credentials. Invalid username or password."  

I observed the following accounts as being invalid:  
4
6
11
13
15
18
22
26
27
28
29
30
31
36

**Comment by InventivetalentDev** [comment]
Closing this, due to affected accounts being deactivated.
