### ISSUE TITLE
[SkinChanger] There are no accounts avaible

### ISSUE THREAD

**Issue by brutalzinn** [MineSkin/api.mineskin.org#71]
Hello.
I am using windows server 2008 64 bit, node js and mongo db. When I send a file, or try changing the skin, this error appears in the console.

image link :   https://ibb.co/bH9bZ9X

**Comment by InventivetalentDev** [comment]
You need Minecraft accounts for MineSkin to work. Please use the api available at api.mineskin.org, as it provides the required accounts.

**Comment by brutalzinn** [comment]
But how do I get these accounts? I have an account on mojang. I would like to have my own api, because I will implement it in some projects.

**Comment by InventivetalentDev** [comment]
You can easily implement the official API in your project. The documentation is in the Wiki,  

You simply need more than one account, which mineskin provides.
